config/routes.rb
PSDB::Application.routes.draw do

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  resources :user_sessions, :only=> [:new, :create, :destroy]

  get "dynamic_images/showImage"
  get "dynamic_images/showPlot"
  get "dynamic_images/showMultiPlot"
  get "dynamic_images/showSeriesPlot"

  resources :experiments do
    resources :attachments, :only => [:show, :new, :create, :edit, :update, :destroy]
  end

  match 'shots/report/:id' => 'shots#report'
 
  resources :shots, :only => [:show, :edit, :update, :index] do
    resources :attachments, :only => [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :instances, :only => [:show, :index]
  resources :instancevaluesets, :only => [:show, :index]
  resources :users

  get "instancevalues/exportImage"
  get "instancevalues/exportPlot"

  get "statistics/overview"
  get "statistics/calendar"

  get "pages/start"
  get "pages/about"
  get "pages/changelog"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root :to => 'user_sessions#new' #"pages#start"
  # See how all your routes lay out with "rake routes"
end

app/models/instancevalueset.rb
require 'gnuplot'
require 'tempfile'
# This model represents a set of measurement data (represented by Instancevalue)
# of a particular Instance for a certain Shot. In addition this model contains a
# version number which is used to identify a certain API version of the underlying
# Instancevalues. It is set by the LabVIEW interface. The web applicataion uses this
# number to correctly display / interpret the measurement data in the class-specific
# views (e.g. found in <tt>views/instancevaluesets/<classtype>/_short_<version number>.html.erb</tt>).
#
# == Schema Information
#
# Table name: instancevaluesets
#
#  id          :integer(38)     not null, primary key
#  shot_id     :integer(38)     not null
#  instance_id :integer(38)     not null
#  version     :integer(38)     not null
#  created_at  :datetime
#  updated_at  :datetime
#
# == Validations
# The following validations exist:
# * It must refer to a valid shot id.
# * It must refer to a valid instance id.

class Instancevalueset < ActiveRecord::Base
  attr_accessible :shot_id, :instance_id, :version
  belongs_to :shot
  belongs_to :instance
  has_many :instancevalues

  validates :version, :presence => true

  validates :shot, :presence => true
  validates :instance, :presence => true
# Return a string value from an Instancevalue of a given name which is associated to
# the Instancevalueset. If the name is not found or the Instancevalue of with this name is
# not a string value, nil is returned.
# parameterName:: name of the parameter (= name field of the Instancevalue) to be returned
# options:: 
# [:strip=>true] remove leading and trailing whitespaces of the string.
# [:upcase=>true] return the upcase version of the string.
  def getStringParameter(parameterName,options={})
    parameterData=self.instancevalues.find_by_name(parameterName)
    if (parameterData.nil?)
      return nil
    else
      if parameterData.datatype.name!="string"
        return nil
      end
      stringData=parameterData.data_string
      if (stringData.nil?)
        return nil
      end
      if options[:strip]==true
        stringData.strip!
      end
      if options[:upcase]==true
        stringData.upcase!
      end
      return stringData
    end
  end
# Return a boolean value from an Instancevalue of a given name which is associated to
# the Instancevalueset. If the name is not found or the Instancevalue of with this name is
# not a boolean value, nil is returned.
# parameterName:: name of the parameter (= name field of the Instancevalue) to be returned
# options:: currently none
  def getBooleanParameter(parameterName,options={})
    parameterData=self.instancevalues.find_by_name(parameterName)
    if (parameterData.nil?)
      return nil
    else
      if parameterData.datatype.name!="boolean"
        return nil
      end
      result=parameterData.data_numeric>0 ? true : false
      return result
    end
  end
# Return a numeric value from an Instancevalue of a given name which is associated to
# the Instancevalueset. If the name is not found or the Instancevalue of with this name is
# not a numeric value, nil is returned.
# parameterName:: name of the parameter (= name field of the Instancevalue) to be returned
# options:: currently none
  def getNumericParameter(parameterName,options={})
    parameterData=self.instancevalues.find_by_name(parameterName)
    if (parameterData.nil?)
      return nil
    else
      if parameterData.datatype.name!="numeric"
        return nil
      end
      return parameterData.data_numeric
    end
  end
# Helper function for handling instances of the class type PH_Sixpack.
#
# The parameter names of of a Sixpack have a syntax such as <tt>Axis 0:Position</tt>.
# This function looks for all parameter names and returns a (sorted) list of found axes
# such as <tt>["Axis 1","Axis 3","Axis4"]</tt>.
  def getAxesNumbers
    foundAxes=Set.new
    parameters=self.instancevalues.select(:name)
    parameters.each do |parameter|
      axisName=parameter.name.split(":")[0]
      if (!axisName.empty?)
        foundAxes.add(axisName)
      end
    end
    return foundAxes.sort.to_a
  end
# Helper function fo handling instances of the class type PH_VacuumControl.
#
# The parameter names of of a VacuumControl have a syntax such as <tt>Channel 0:<Name>:<Parameter></tt>.
# This function looks for all parameter names and returns a list of found channels such as
# <tt>["Channel 1:Telescope 1","Channel 4:PA Exit"]</tt>.
  def getVacuumChannels
    foundChannels=Set.new
    parameters=self.instancevalues.select(:name)
    parameters.each do |parameter|
      parameterList=parameter.name.split(":")
      channelNumber=parameterList[0]
      channelName=parameterList[1]
      channel=""
      if channelNumber.present?
        channel += channelNumber+":"
      end
      if channelName.present?
        channel += channelName
      end
      if channel.present?
        foundChannels.add(channel)
      end
    end
    return foundChannels
  end
  def analyzePulsedPowerStatus
    currentState=:unknown
    voltage=getNumericParameter("Voltage")
    timeout=getStringParameter("Timeout",:upcase=>true)
    if voltage==-1.0
      currentState=:off
    elsif timeout=="NONE"
      currentState=:on
    else
      currentState=:error
    end
    return currentState
  end
  def generateMultiPlot(plotParameterNames,options={})
    tempFile=Tempfile.new(['multiplotImage','.png'])
    plotOptions={:width=>200, :height=>100, :imagetype=> "png"}
    plotOptions=plotOptions.merge(options)
    dataAvailable=false
    Gnuplot.open do |gp|
      Gnuplot::Plot.new( gp ) do |plot|
        plot.terminal "#{plotOptions[:imagetype]} small size #{plotOptions[:width]},#{plotOptions[:height]}"
        plot.output tempFile.path
        if (plotParameterNames.length!=0)
          instanceValue=self.instancevalues.find_by_name(plotParameterNames[0])
          if instanceValue
            axisDescriptions=instanceValue.generatePlotAxisDescriptions()
            plot.xlabel axisDescriptions[:xlabel]
            plot.ylabel axisDescriptions[:ylabel]
          end
        end
        plotParameterNames.each do |plotParameterName|
          plotData=getPlotDataSet(plotParameterName)
          if !plotData.nil?
            plot.data << plotData
            dataAvailable=true
          end
        end
      end
    end
    tempFile.rewind
    if dataAvailable
      returnImage=Magick::Image.read(tempFile.path)[0]
      tempFile.close
      tempFile.unlink
      return returnImage
    else
      tempFile.close
      tempFile.unlink
      return ""
    end
  end

  def getPlotDataSet(parameterName,options={})
    instanceValue=self.instancevalues.find_by_name(parameterName)
    if (instanceValue.nil?)
      return nil
    else
      plotDataSet=instanceValue.generatePlotDataSet()
      return plotDataSet
    end
  end
end

app/controllers/instancevaluesets_controller.rb
# This controller is responsible for handling Instancevaluesets.
# The index action allows for displaying a list of measurement data of a
# particular device for a set of shots.
class InstancevaluesetsController < ApplicationController
  def index
    selectedValueSets=Instancevalueset
    if (params[:instance_id].present?)
      selectedValueSets=selectedValueSets.where(:instance_id => params[:instance_id])
      @instanceId=params[:instance_id]
    end
    if (params[:from_date].present?)
      begin
       startDate=Date.parse(params[:from_date]).to_s+" 00:00:00"
        selectedValueSets=selectedValueSets.where("instancevaluesets.created_at >= ?",startDate)
        params[:from_date]=Date.parse(params[:from_date]).to_s
      rescue ArgumentError
        params[:from_date]=""
      end
    end
    if (params[:to_date].present?)
      begin
        endDate=Date.parse(params[:to_date]).to_s+" 23:59:59"
        selectedValueSets=selectedValueSets.where("instancevaluesets.created_at <= ?",endDate)
        params[:to_date]=Date.parse(params[:to_date]).to_s
      rescue ArgumentError
        params[:to_date]=""
      end
    end
    @instanceValueSets=selectedValueSets.order("shot_id DESC").paginate(:page => params[:page])
    datatype=Datatype.find_by_name("numeric")
    if (datatype)
      datatypeId=datatype.id
      availableParameters=selectedValueSets.joins(:instancevalues).where("datatype_id=?",datatypeId).
        select("instancevalues.name").group("instancevalues.name")
    else
      availableParameters=[]
    end
    @doPlot=false
    if (availableParameters.length!=0)
      @doPlot=true
      @parameterArray=[]
      count=0
      availableParameters.each do |availableParameter|
        @parameterArray << [availableParameter.name,count]
        count+=1
      end
      if (params[:plotParameter].present?)
        # check if parameterNr still valid
        if params[:plotParameter].to_i<@parameterArray.length
          selectedPlotParameter=@parameterArray[params[:plotParameter].to_i][0]
        else
          selectedPlotParameter=availableParameters.first.name
          params[:plotParameter]=0
        end
      else
        selectedPlotParameter=availableParameters.first.name
        params[:plotParameter]=0
      end
      parameterValues=selectedValueSets.joins(:instancevalues).
          where("name=?",selectedPlotParameter).
          select("shot_id,instancevalues.data_numeric,instancevalues.data_string")
      xValues=[]
      yValues=[]
      parameterValues.each do |parameterValue|
        xValues << parameterValue.shot_id
        yValues << convertUnitValue(parameterValue.data_numeric,parameterValue.data_string)
      end
      @yLabel=selectedPlotParameter
      baseUnit=getBaseUnit(parameterValues.last.data_string)
      if (!baseUnit.nil?)
        if (!baseUnit.empty?)
          @yLabel+=" ["+baseUnit+"]"
        end
      end
      @xyValues=[xValues,yValues]
    end
    @formData=params
  end

  def show
    @showRaw=params[:rawView]=="true" ? true : false
    @instanceValueSet=Instancevalueset.find_by_id(params[:id])
  end
end

app/helpers/instancevaluesets_helper.rb
require "gnuplot"
# This module provides helper functions for displaying measurment data of an Instance (which is represented by an
# Instancevalueset).
module InstancevaluesetsHelper
# Display a parameter of a given Instancevalueset.
#
# If an Instancevalue with the correct name belonging to the Instancevalueset is found the corresponding partial
# is called. Otherwise an error message (or likewise an error icon) ist displayed.
# instanceValueSet:: Instancevalueset to display from
# parameterName:: name of the Instancevalue to be displayed
# options::
# All options are forwarded the helper function InstancevaluesHelper::displayValue.
# In addtion the options :iconIfNotFound is defined which shows an error icon instead of an error message
# if the Instancevalue with the given name was not found.
  def displayParameter(instanceValueSet,parameterName,options={})
    parameterData=instanceValueSet.instancevalues.find_by_name(parameterName)
    if (parameterData.nil?)
      if options[:iconIfNotFound]==true
        return image_tag "icon_ERROR.png", {:style=>"vertical-align:middle"}
      else
        return "parameter <#{parameterName}> not found"
      end
    else
      displayValue(parameterData,options)
    end
  end
# Display a short view representation of an Instancevalueset.
#
# This functions calls the corresponding partial depending on the class type of the instance following
# the naming scheme <tt>/app/views/instancevaluesets/<classType>/_short_<versionNumber>.html.erb</tt>
  def displayValueSetShort(instanceValueSet,options={})
    classType=instanceValueSet.instance.classtype.name
    valueSetVersion=instanceValueSet.version
    partialName="/instancevaluesets/#{classType}/short_#{valueSetVersion}"
    partialFileName=::Rails.root.to_s+"/app/views/instancevaluesets/"+classType+
      "/_short_"+valueSetVersion.to_s+".html.erb"
    if !File.exists?(partialFileName)
      return "no view defined"
    else
      render partialName, :instanceValueSet => instanceValueSet, :options=>options
    end
  end
# Generate an xy plot from an array of data sets.
#
# In contrast to Instancevalue::generatePlot this function accepts an array of xy data to be plotted as
# a set of lines in one graph.
# xyData:: array of xy data
# options::
# [:width] width the the plot in pixels (default is 200)
# [:height] height of the plot in pixels (default is 100)
# [:imagetype] type of the generated image file (defaults to "png")
# [:xlabel] label of the x axis (defaults to "")
# [:ylabel] lable of the y axis (defaults to "")
  def generateSeriesPlot(xyData, options={})
    plotOptions={:width=>200, :height=>100, :imagetype=> "png", :xlabel=> "", :ylabel=> ""}
    plotOptions=plotOptions.merge(options)
    Gnuplot.open do |gp|
      Gnuplot::Plot.new( gp ) do |plot|
        plot.terminal "#{plotOptions[:imagetype]} small enhanced size #{plotOptions[:width]},#{plotOptions[:height]} crop"
        plot.output Rails.root.to_s+"/public/series.png"
        plot.ylabel plotOptions[:ylabel]
        plot.xlabel plotOptions[:xlabel]
        plot.boxwidth 0.5
        plot.grid ""
        plot.data << Gnuplot::DataSet.new( xyData ) do |ds|
          ds.with = "boxes fill solid 0.5"
          ds.notitle
        end
      end
    end
  end
end

app/views/instancevaluesets/_instancevalueset_detailed.html.erb
<% classType=instanceValueSet.instance.classtype.name %>
<% valueSetVersion=instanceValueSet.version %>
<% partialName="/instancevaluesets/#{classType}/detailed_#{valueSetVersion}" %>
<% partialFileName=::Rails.root.to_s+"/app/views/instancevaluesets/"+classType+"/_detailed_"+valueSetVersion.to_s+".html.erb" %>
<% if !File.exists?(partialFileName) %>
  <% partialName="instancevalueset_detailed_unknown" %>
<% end %>
<%= render partialName, :instanceValueSet => instanceValueSet %>

app/views/instancevaluesets/_instancevalueset_detailed_unknown.html.erb
<h3>No specific view for class < <%= instanceValueSet.instance.classtype %>
Version <%=instanceValueSet.version %> > defined..showing generic data</h3>
<table>
  <thead>
    <tr>
      <th class="span-6">Name</th>
      <th class="span-3">Datatype</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    <% instanceValueSet.instancevalues.includes(:datatype).each do |instancevalue| %>
      <tr>
        <td><%= instancevalue.name %></td>
        <td><%= instancevalue.datatype %></td>
        <td><%= displayValue(instancevalue) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/instancevaluesets/_instancevalueset_short.html.erb
<%
  classType=instanceValueSet.instance.classtype.name
  valueSetVersion=instanceValueSet.version
  partialName="/instancevaluesets/#{classType}/short_#{valueSetVersion}"
  partialFileName=::Rails.root.to_s+"/app/views/instancevaluesets/"+classType+"/_short_"+valueSetVersion.to_s+".html.erb"
  if !File.exists?(partialFileName)
%>
<%= render :text => "no view defined" %>
<% else %>
<%= render partialName, :instanceValueSet => instanceValueSet %>
<% end %>

app/views/instancevaluesets/index.html.erb
<h2>Measurement series</h2>
<h3>Filter by date</h3>
<%= form_tag(instancevaluesets_path, :method => "get") do %>
 <%= label_tag(:from_date, "From:") %>
 <%= text_field_tag(:from_date,@formData[:from_date]) %>
 <%= label_tag(:to_date, "to:") %>
 <%= text_field_tag(:to_date,@formData[:to_date]) %>
 <%= hidden_field_tag(:instance_id, @formData[:instance_id]) %>
 <%= hidden_field_tag(:plotParameter, @formData[:plotParameter]) %>
 <%= submit_tag("Filter") %>
<% end %>
<br />
<div class="span-12">
  <%= page_entries_info @instanceValueSets %>
  <%= will_paginate @instanceValueSets %>
  <table>
    <thead>
      <tr>
        <th>Shot #</th>
        <th>Date</th>
        <th>Device</th>
        <th class="span-3">Result</th>
      </tr>
    </thead>
   <tbody>
      <% @instanceValueSets.each do |instanceValueSet| %>
        <tr>
          <td><%= link_to instanceValueSet.shot_id, instanceValueSet.shot %></td>
          <td><%= formatDate(instanceValueSet.shot.created_at) %></td>
          <td><%= link_to instanceValueSet.instance, instanceValueSet %></td>
          <td><%= displayValueSetShort(instanceValueSet) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="span-12 last">
  <% if @doPlot %>
    <div class="box">
        <%= form_tag(instancevaluesets_path, :method => "get") do %>
          <%= label_tag(:plotParameter, "Plot parameter:") %>
          <%= select_tag(:plotParameter,options_for_select(@parameterArray,@formData[:plotParameter])) %>
          <%= hidden_field_tag(:instance_id, @formData[:instance_id]) %>
          <%= hidden_field_tag(:from_date, @formData[:from_date]) %>
          <%= hidden_field_tag(:to_date, @formData[:to_date]) %>
          <%= submit_tag("Draw") %>
        <% end %>
      </div>
    <% generateSeriesPlot(@xyValues,{:width=>450,:height=>300,:xlabel=>"shot#",:ylabel=>@yLabel}) %>
    <img src= <%= url_for "dynamic_images/showSeriesPlot" %> />
  <% else %>
    No numerical data for plot available
  <% end %>
</div>

app/views/instancevaluesets/show.html.erb
<h2>
  <%= @instanceValueSet.instance.name %>  Shot# <%= @instanceValueSet.shot_id %>
</h2>
<% if @showRaw %>
  <%= render 'instancevalueset_detailed_unknown', :instanceValueSet => @instanceValueSet %>
<% else %>
  <%= render 'instancevalueset_detailed', :instanceValueSet => @instanceValueSet %>
<% end %>
<% if Rails.env.development? %>
  <br />
  <%= link_to "Raw development view", instancevalueset_path(@instanceValueSet, :rawView=>true) %>
<% end %>