config/routes.rb
PSDB::Application.routes.draw do

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  resources :user_sessions, :only=> [:new, :create, :destroy]

  get "dynamic_images/showImage"
  get "dynamic_images/showPlot"
  get "dynamic_images/showMultiPlot"
  get "dynamic_images/showSeriesPlot"

  resources :experiments do
    resources :attachments, :only => [:show, :new, :create, :edit, :update, :destroy]
  end

  match 'shots/report/:id' => 'shots#report'
 
  resources :shots, :only => [:show, :edit, :update, :index] do
    resources :attachments, :only => [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :instances, :only => [:show, :index]
  resources :instancevaluesets, :only => [:show, :index]
  resources :users

  get "instancevalues/exportImage"
  get "instancevalues/exportPlot"

  get "statistics/overview"
  get "statistics/calendar"

  get "pages/start"
  get "pages/about"
  get "pages/changelog"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root :to => 'user_sessions#new' #"pages#start"
  # See how all your routes lay out with "rake routes"
end

app/models/experiment.rb
# This model represents an experiment to which a Shot can refer to.
# Experiments can only be created, modified, and deleted using the web
# interface. Furthermore file attachments can be added.
#
# == Schema Information
#
# Table name: experiments
#
#  id          :integer(38)     not null, primary key
#  name        :string(30)      not null
#  active      :boolean(1)      default(TRUE)
#  description :string(255)     not null
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#
# == Validations
# The following validations exist:
# * The name (such as +P043+) must be unique.
# * The name must not exceed 30 characters.
# * The description must not exceed 255 characters.
# * It cannot be deleted if a Shot refers to it.
#
class Experiment < ActiveRecord::Base

  attr_accessible :name, :description, :active

  # paginate results
  cattr_reader :per_page
  @@per_page = 15

  has_many :shots
  has_many :attachments, :as => :attachable, :dependent => :destroy
  has_many :experiment_owners, :dependent => :destroy
  has_many :users, :through => :experiment_owners

  validates :name, :presence => true,
                   :length => { :maximum => 30 },
                   :uniqueness => { :case_sensitive => false }

  validates :description, :presence => true,
                          :length => { :maximum => 255 }

  before_destroy :check_if_shots_associated

# Return a list of beam times. A beam time is a period of time in which shots
# are refered to this experiment. The beam time start with the date of the first
# shot referring this experiment. If two shots are more than a given time separated
# from each other this is interpreted as a new beam time of the same experiment.
# This functions returns an array of hash lists of the found beam times.
#
# Example of a return value:
#  beamtimes=[{:firstId=1,:lastId=>10,:firstDate=>1.1.2010,:lastDate=>4.1.2010},
#             {:firstId=20,:lastId=>25, :firstDate=>8.2.2010,:lastDate=>9.2.2010}]
# This experiment would have two beam times. One in january and one in february 2010.
#
# minimumTimeBetweenBeamTimes::
# if two shot dates are separated more than this time they are accounted to a new
# beam time.
  def getBeamtimes(minimumTimeBetweenBeamTimes=5.days)
    if self.shots.empty?
      return []
    end
    queryString="
        select nextTable.created_at as t1,
               currentTable.created_at as t2,
               currentTable.id as currentid,
               nextTable.id as nextid
        from (select * from shots where experiment_id=%d) currentTable
        join (select * from shots where experiment_id=%d) nextTable
        on nextTable.id=(select min(id) from
          (select * from shots where experiment_id=%d) dummyTable where id>currentTable.id)" % [self.id,self.id,self.id]
    durations=Shot.find_by_sql(queryString)
    beamtimes=[]
    beamtime={:firstId=>self.shots.first.id, :firstDate=>self.shots.first.created_at}
    durations.each do |d|
      difference=d.t1-d.t2
      if(difference>minimumTimeBetweenBeamTimes)
        beamtime[:lastId]=d.currentid
        beamtime[:lastDate]=d.t2
        beamtimes << beamtime
        beamtime={:firstId=>d.nextid, :firstDate=>d.t1}
      end
    end
    beamtime[:lastId]=self.shots.last.id
    beamtime[:lastDate]=self.shots.last.created_at
    beamtimes << beamtime
    return beamtimes
  end
# Return the name of the experiment. This function was added to simplify views.
  def to_s
    return self.name
  end

private
  def check_if_shots_associated
    if (!shots.empty?)
      errors.add(:base, "cannot be deleted with shots associated")
      return false
    else
      return true
    end
  end
end

app/controllers/experiments_controller.rb
# This restful controller handles the Experiment resources.
# Experiments can be displayed, created, and modified. Deletion of Experiments
# is only possible if no shots are related to it.
#
# In addition it is possible to add file attachments to a particular experiment. This
# functionality is handles by the AttachmentsController.
class ExperimentsController < ApplicationController
  filter_access_to :all, :attribute_check => true
  filter_access_to :index, :attribute_check => false

  def index
    @experiments = Experiment.with_permissions_to(:read).
      paginate(:page => params[:page], :include=>[:attachments])
    @pageTitle="Experiments"
  end
  def show
    @experiment=Experiment.find_by_id(params[:id])
    if @experiment
      @pageTitle=@experiment.name
      @beamtimes=@experiment.getBeamtimes(7.days)
    else
      flash[:error] = "Experiment not found"
      redirect_to experiments_path
    end
  end

  def new
    @experiment=Experiment.new(:active => true)
    @user=User.new
    @pageTitle="Add new experiment"
  end
  def create
    if params[:cancel]
      flash[:info] = "Experiment creation cancelled"
      redirect_to experiments_path
      return
    end
    @experiment = Experiment.new(params[:experiment])
    if @experiment.save
      @user=User.new
      @user.login=@experiment.name
      @user.realname=params[:experiment][:user][:realname]
      @user.email=params[:experiment][:user][:email]
      @user.password="abcabc"
      @user.password_confirmation="abcabc"
      role=@user.roles.new(:title=>"experimentalist")
      if @user.save && role.save
        @owner=@experiment.experiment_owners.create!(:user_id=>@user.id)
        flash[:success] = "Experiment and user account successfully created"
        redirect_to experiments_path
      else
        flash[:error] = "Error setting up user account for experiment"
        redirect_to experiments_path
      end
    else
      @pageTitle = "Add new experiment"
      render 'new'
    end
  end
  def edit
    @experiment=Experiment.find_by_id(params[:id])
    if @experiment
      @user=@experiment.users.first || @experiment.users.new
      @pageTitle="Edit experiment "+@experiment.name
    elsif
      flash[:error] = "Experiment not found"
      redirect_to experiments_path
    end
  end
  def update
    @experiment = Experiment.find_by_id(params[:id])
    if !@experiment
      flash[:error] = "Experiment not found"
      redirect_to experiments_path
      return
    end
    if params[:cancel]
      flash[:info] = "Experiment update canceled"
      redirect_to experiment_path(@experiment)
      return
    end
    @user=@experiment.users.first
    @user.login=@experiment.name
    @user.realname=params[:experiment][:user][:realname]
    @user.email=params[:experiment][:user][:email]
    if @experiment.update_attributes(params[:experiment]) && @user.save!
      @experiment.experiment_owners.create(:user_id=>@user.id)
      flash[:success] = "Experiment successfully updated"
      redirect_to experiments_path
    else
       @experiment.reload
       @pageTitle="Edit experiment "+@experiment.name
       render 'edit'
    end
  end
  def destroy
    experiment=Experiment.find_by_id(params[:id])
    if experiment
      if experiment.destroy
        flash[:success] = "Experiment successfully deleted"
      else
        flash[:error] = "Error while deleting experiment"
      end
    else
      flash[:error] = "Experiment not found"
    end
    redirect_to experiments_path
  end
end

app/views/experiments/_experiment.html.erb
<%= form_for @experiment do |e| %>
  <%= render 'shared/error_messages', :object => e.object %>
  
  <%= e.label :name %><br/>
  <%= e.text_field :name %><br/>
  <%= e.label :description %><br/>
  <%= e.text_area :description %><br/>
  <%= e.fields_for(user) do |u| %>
    <%= u.label :realname, "Contact person" %><br/>
    <%= u.text_field :realname %><br/>
    <%= u.label :email %><br/>
    <%= u.email_field :email %><br/>
  <% end %>
  <%= e.label :active, "Active Experiment?" %>
  <%= e.check_box(:active) %><br/>
  <div class="actions">
    <%= e.submit "Save Experiment" %>
    <%= e.submit "Cancel", :name => "cancel" %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<h2>Experiment <%= @experiment.name %></h1>
<%= render @experiment, :user=>@user %>

app/views/experiments/index.html.erb
<h2>Available Experiments</h2>
<%= link_to 'Add new experiment', new_experiment_path if permitted_to? :create, :experiments %>
<%= will_paginate @experiments %>
<table border="0" cellspacing="0" cellpadding="0">
  <thead>
    <tr>
      <th class="span-2">Name</th>
      <th class="span-10">Description</th>
      <th class="span-4">Contact person</th>
      <th class="span-4">Contact email</th>
      <th class="span-1">Active?</th>
      <th class="span-1"></th>
      <th class="span-2"></th>
    </tr>
  </thead>
  <tbody>
    <% @experiments.each do |experiment| %>
      <tr>
        <td><%= link_to experiment, experiment %></td>
        <td><%= experiment.description %></td>
        <td><% if experiment.users.present? %>
              <%= experiment.users.first.realname %>
            <% else %>
              not assigned
            <% end %></td>
        <td><% if experiment.users.present? %>
              <%= experiment.users.first.email %>
            <% else %>
              not assigned
            <% end %></td>
        <td><%= experiment.active? ? 'yes' : 'no' %></td>
        <td><% if experiment.attachments.present? %>
              <%= image_tag 'paperclip.png' %>
        <% end %></td>
        <td><%= link_to 'Edit', edit_experiment_path(experiment) if permitted_to? :update, experiment %>
            <% if experiment.attachments.present?
              @confirmation="There are documents attached to the experiment, which WILL BE LOST if the experiment is deleted. Are You sure you want to do this?"
               else
              @confirmation="Are You sure?"
              end %>
              <%= link_to "Delete", experiment, :confirm => @confirmation, :method => :delete if (permitted_to? :destroy, experiment) && (experiment.shots.empty?) %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @experiments %>

app/views/experiments/new.html.erb
<h2>Add new experiment</h2>
<%= render @experiment, :user=>@user %>

app/views/experiments/show.html.erb
<h2>Experiment <%= @experiment %></h2>
<div class="span-24 last" id="topbox">
  <div class="span-8" id="general">
    <div class="box">
      <strong>Description: </strong> <%= @experiment.description %><br>
      <strong>Created at: </strong> <%= formatDate(@experiment.created_at) %><br>
      <strong>Updated at: </strong> <%= formatDate(@experiment.updated_at) %><br>
      <strong>Active: </strong> <%= @experiment.active? ? 'yes' : 'no' %><br>
      <%= link_to "Edit", edit_experiment_path(@experiment) %>
    </div>
  </div>
  <div class="span-16 last" id="attachments">
    <div class="box">
      <%= render 'attachments/index', :parent => @experiment %>
    </div>
  </div>
</div>
<hr>
<h3>Shot statistics</h3>
<% nrOfShots=@experiment.shots.count %>
<% if (nrOfShots>0) %>
  <strong>First shot was: </strong> <%= formatDate(@experiment.shots.minimum("created_at")) %><br>
  <strong>Latest shot was: </strong> <%= formatDate(@experiment.shots.maximum("created_at")) %><br>
  <strong># of beamtimes: </strong> <%= @beamtimes.length() %><br>
  <div class="span-9 append-15 last">
    <table>
      <thead>
        <tr>
          <th class="span-5">Date</th>
          <th class="span-2">first shot#</th>
          <th class="span-2">last shot#</th>
        </tr>
      </thead>
      <tbody>
       <% @beamtimes.each do |beamtime| %>
        <tr>
         <td><% firstDate=formatDate(beamtime[:firstDate], {:dateOnly => true})
                lastDate=formatDate(beamtime[:lastDate], {:dateOnly => true})
                dateSpan=firstDate+" - "+lastDate %>
          <%= link_to dateSpan, shots_path({:from_date=>firstDate,
                                            :to_date=>lastDate,
                                            :selectedExp=>@experiment.id}) %>
          </td>
         <td><%= beamtime[:firstId] %></td>
         <td><%= beamtime[:lastId] %></td>
        </tr>
       <% end %>
      </tbody>
    </table>
  </div>
  <div class="span-5 last">
  <table border="0" cellspacing="0" cellpadding="0">
    <thead>
      <tr>
        <th class="span-3">Shot type</th>
        <th class="span-2"># of shots</th>
      </tr>
    </thead>
    <tbody>
      <% Shottype.all.each do |shottype| %>
        <% shotNr=@experiment.shots.where(:shottype_id => shottype).count %>
        <% if shotNr>0 %>
          <tr>
            <td><%= shottype %></td>
            <td><%= shotNr %></td>
          </tr>
        <% end %>
      <% end %>
      <tr>
        <td><strong>Total</strong></td>
        <td><strong><%= nrOfShots %></strong></td>
      </tr>
    </tbody>
  </table>
  </div><br>
<% else %>
  No shots connected with this experiment.<br>
<% end %>
<hr>
<%= link_to "Back to experiments", experiments_path %>